config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :events
  resources :users
  resources :enrollments
  
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :event
  belongs_to :user
  belongs_to :host, class_name: "User"
  belongs_to :invitee, class_name: "User"
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :host, class_name: "User", foreign_key: 'user_id'
  has_many :enrollments
  has_many :attendee, through: :enrollments, source: :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :enrollments
  has_many :attended_events, through: :enrollments, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController

  def create
    event = Event.find(params[:event_id])
    enrollment = current_user.enrollments.build(event_id: event.id, user_id: params[:user_id])

    if enrollment.save
      flash[:notice] = "Invitation sent!"
      redirect_to users_path(event_id: event.id)
    else
      flash[:alert] = 'Ooops! Something went wrong...'
      redirect_to event_path(event)
    end
  end

  def update
    @event = Event.find(params[:event_id])
    @enrollment = Enrollment.find_by(event_id: params[:event_id], user_id: current_user.id)

    flash[:notice] = "Thank you for signing up for the #{@event.title}!"
    redirect_to event_path(@event)
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.all
  end

  def show 
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.events.build
  end

  def create 
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:success] = "Event '#{@event.name}' created!"
      redirect_to @event
    else
      flash[:alert] = "Some error!"
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :date, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users_events = Event.all.includes(:creator)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div>

    <%= form.label "Event Title" %><br>
    <%= form.text_field :title %><br>
   <% event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>

    <%= form.label "Event Description" %><br>
    <%= form.text_field :description %><br>
   <% event.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>

    <%= form.label "Event Location" %><br>
    <%= form.text_field :location %><br>
    <% event.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>

  <%= form.label "Event Date" %><br>
  <%= form.date_select :date %>

  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/events/index.html.erb
<center>

<div class="top">
  <div class="section">
    <h2 class="title is-2">Upcoming Events</h2>
    <div class="columns">
      <% @events.each do |event| %>
        <div class="column is-3">
          <div class="card">
            <header class="card-header">
              <%= link_to event.title, event_path(event), class: "card-header-title is-centered" %>
            </header>
            <div class="card-content">
              <div class="content has-text-justified">
                <%= event.description.truncate_words(12) %>
              </div>
            </div>
            <footer class="card-footer">
              <p class="card-footer-item is-narrow"><%= event.date %></p>
              <p class="card-footer-item"><%= event.location %></p>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

</center> 

app/views/events/new.html.erb
<h1>Create a new event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<center>
  <div>
    <%= @event.title %><br>
    <%= @event.description %><br>
    <%= @event.date %><br>
  </div>

   <% if @event.host == current_user %>
            <%= button_to "Invite", root_path,  class: "button is-info is-large is-fullwidth" %>
          <% else %>
            <%= button_to "Enroll", enrollments_path(event_id: @event.id, user_id: current_user.id), class: "button is-primary is-large is-fullwidth" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4">Eventdim</h1>
        <% end %>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
              <% if current_user %>
                <%= link_to "Create event", new_event_path, class: "button is-white" %>
              </p>
                <p class="control">
                  <%= link_to current_user.email, user_path(current_user), class: "button is-white" %>
                </p>
                <p>
                  <%= button_to "Logout", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "button is-white" %>
                </p>
              <% else %>
                <p class="control">
                  <%= link_to 'Sign In', new_user_session_path, class: "button is-white" %>
                </p>
						    <p class="control">
                  <%= link_to 'Sign Up', new_user_registration_path, class: "button is-white" %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>

  <footer class="footer">
   
  </footer>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<center>
  <h1>your events!</h1> 

    <%= @users_events.each do |event| %> 
      <%= event.title %><br> 
      <%= event.description %><br> 
      <%= event.location %><br> 
      <%= event.date %><br> 
    <% end %> 
</center>